-- Run this once in your Supabase project's SQL Editor (see README.md for steps).

create table if not exists workout_logs (
  id bigint generated by default as identity primary key,
  entry_date date not null,
  day_name text not null,
  session_name text not null,
  exercise_name text not null,
  field1_label text,
  value1 text,
  field2_label text,
  value2 text,
  created_at timestamptz not null default now()
);

alter table workout_logs enable row level security;

-- The app's public key may only add new rows...
create policy "Allow public insert" on workout_logs
  for insert
  to anon
  with check (true);

-- ...and read existing rows (for the History page).
-- It cannot update or delete anything.
create policy "Allow public read" on workout_logs
  for select
  to anon
  using (true);
